In [1]:
vent <- read.table("C:/Users/hp/Desktop/cppp/TimeSeriesAnalysis/p2s6/ventilation.txt")
head(vent)

  V1
1 11.28
2 13.26
3 15.07
4 15.32
5 17.73
6 13.95

In [2]:
vent <- read.table("C:/Users/hp/Desktop/cppp/TimeSeriesAnalysis/p2s6/ventilation.txt", header=TRUE)
head(vent)

  X11.28
1 13.26
2 15.07
3 15.32
4 17.73
5 13.95
6 15.77

In [3]:
vent <- read.table("C:/Users/hp/Desktop/cppp/TimeSeriesAnalysis/p2s6/ventilation.txt")
head(vent)

  V1
1 11.28
2 13.26
3 15.07
4 15.32
5 17.73
6 13.95

In [ ]:
library(TSA)
vent <- ts(vent$vent, start=1)
colnames(vent) <-c('vent')
vent <- ts(vent$vent, start=1, frequency=1)
plot(vent)

In [ ]:
model <- lm(vent$vent ~ vent$time) 
model <- lm(vent ~ time) 
model <- lm(vent ~ time(vent)) 
summary(model)
plot(vent)
abline(model, col='red')

In [ ]:
res <- residuals(model)
plot(res)
abline(h=0, col='blue')

In [ ]:
hist(res)

In [ ]:
hist(res, breaks=10)

In [ ]:
hist(res, breaks=100)
hist(res, breaks=20)

In [ ]:
shapiro.test(res)

In [ ]:
acf(res)

In [ ]:
qqnorm(res)

In [ ]:
res <- residuals(model)
hist(res, breaks=20)

In [ ]:
qqnorm(res)
acf(res)
plot(res, type='l')
abline(h=0, col='blue')

In [ ]:
shapiro.test(res)